#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import time
 
def createDaemon():
    pid = os.fork()
    if pid > 0:
        f = open('/var/run/radkickd.pid','w')
        f.write(str(pid)+"\n")
        f.close()
        sys.exit()

    else : 
        os.system('mplayer -playlist http://yp.shoutcast.com/sbin/tunein-station.pls?id=172098')
        while True:
            time.sleep(1) 

if __name__ == '__main__':
    createDaemon()
