#!/usr/bin/python

import os
import sys
 
def createDaemon():
    # フォークして子プロセスのPIDを返してきた方（親）でpidを保持
    pid = os.fork()
    if pid > 0:
        f = open('/var/run/radkickd.pid','w')
        f.write(str(pid)+"\n")
        f.close()
        sys.exit()

    else : # 子プロ
        os.system('mplayer -playlist http://yp.shoutcast.com/sbin/tunein-station.pls?id=172098')
        while True:
            
 
if __name__=='__main__': 
        createDaemon()